spring:
  application:
    name: discodeit

  boot:
    admin:
      client:
        url: http://localhost:9090

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers

server:
  port: 8080

logging:
  level:
    com.sprint.mission.discodeit: debug
