spring:
  application:
    name: discodeit

  boot:
    admin:
      client:
        instance:
          name: discodeit

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  profiles:
    active: prod

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB


discodeit:
  repository:
    type: jcf     # jcf | file
    file-directory: data

  storage:
    type: ${STORAGE_TYPE:local} # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
#      access-key: ${AWS_S3_ACCESS_KEY}
#      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

logging:
  level:
    com.sprint.mission.discodeit: info


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  info:
    env:
      enabled: true


info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0

  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}

    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}

    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}

    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}

